---
title: "EDA of Colombia's presidential election polls and results"
output:
  html_document:
    keep_md: true
    code_folding: hide
---


# Read and tidy data
```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)

start_date <- as.Date("2022-03-13")
candidates <- c(
    "Petro",
    "Gutierrez",
    "Hernandez",
    "Fajardo"
)

prefix <- "https://raw.githubusercontent.com/nelsonamayad/Elecciones-presidenciales-2022/main/"
path <- "Encuestas%202022/encuestas_2022.csv"

df <- paste0(prefix, path) %>%
    readr::read_csv(
        col_types = list(
            encuestadora = col_character(),
            fuente = col_character(),
            link = col_character(),
            muestreo = col_character(),
            tipo = col_character(),
            hipotesis = col_character(),
            fecha = col_date(),
            n = col_integer(),
            .default = col_double()
        )
    ) %>%
    select(
        -n,
        -tasa_respuesta,
        -fuente,
        -hipotesis,
        -muestra_int_voto,
        -margen_error
    ) %>%
    rename(
        pollster = encuestadora,
        date= fecha,
        sample_size = muestra,
        other = otros,
        other_nsnr=ns_nr,
        sample_type = muestreo,
        poll_mode = tipo,
        num_cities = municipios
    ) %>%
    filter(date > start_date) %>%
    tidyr::pivot_longer(
        !c(
            pollster,
            date,
            sample_size,
            link,
            sample_type,
            poll_mode,
            num_cities   
        ),
        names_to = "candidate",
        values_to = "prop"
    ) %>%
    mutate(
        candidate = stringr::str_to_title(
            stringr::str_extract(
                candidate, "[^_]+$"
            )
        ),
        candidate = ifelse(
            candidate %in% candidates,
            candidate,
            "Other"
        ),
        prop = prop / 100
    ) %>%
    group_by(
        pollster,
        date,
        candidate,
        sample_size,
        link,
        sample_type,
        poll_mode,
        num_cities
    ) %>%
    summarise(
        prop=sum(prop, na.rm=TRUE),
        .groups="drop"
    ) %>%
    mutate(
        vote = round(prop * sample_size)
    ) %>%
    relocate(
        poll_mode,
        candidate,
        vote,
        prop,
        .after = date
    ) %>%
    arrange(
        date, pollster, candidate
    )

knitr::kable(head(select(df, -link), 20))
```


# Visualize raw data
```{r message=FALSE}
library(ggplot2)
library(scales)

pollsters <- c(
    "CNC",
    "CELAG",
    "Guarumo",
    "Invamer",
    "MassiveCaller",
    "YanHass"
)

df %>%
    filter(pollster %in% pollsters) %>%
    ggplot(aes(date, prop, color=candidate, shape=pollster)) +
    geom_point(alpha=1) +
    geom_line(alpha=0.2) +
    scale_y_continuous(labels = scales::percent)
```
